import Foundation

enum BrandProductSeed {
    static let us: [BrandProductPreset] = [
        // Red Bull (US)
        BrandProductPreset(
            id: "us-redbull-energy-8_4oz",
            brand: "Red Bull",
            productName: "Red Bull Energy Drink",
            sizeOz: 8.4,
            sizeLabel: "8.4 oz",
            caffeineMg: 80,
            region: "US",
            sourceName: "Red Bull US Q&A",
            sourceType: .brandOfficial,
            sourceURL: "https://www.redbull.com/us-en/energydrink/questions/how-much-caffeine-is-in-a-can-of-red-bull-energy-drink",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .energy
        ),
        BrandProductPreset(
            id: "us-redbull-energy-12oz",
            brand: "Red Bull",
            productName: "Red Bull Energy Drink",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 114,
            region: "US",
            sourceName: "Red Bull US Q&A",
            sourceType: .brandOfficial,
            sourceURL: "https://www.redbull.com/us-en/energydrink/questions/how-much-caffeine-is-in-a-can-of-red-bull-energy-drink",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .energy
        ),
        BrandProductPreset(
            id: "us-redbull-energy-16oz",
            brand: "Red Bull",
            productName: "Red Bull Energy Drink",
            sizeOz: 16.0,
            sizeLabel: "16 oz",
            caffeineMg: 151,
            region: "US",
            sourceName: "Red Bull US Q&A",
            sourceType: .brandOfficial,
            sourceURL: "https://www.redbull.com/us-en/energydrink/questions/how-much-caffeine-is-in-a-can-of-red-bull-energy-drink",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .energy
        ),
        BrandProductPreset(
            id: "us-redbull-energy-20oz",
            brand: "Red Bull",
            productName: "Red Bull Energy Drink",
            sizeOz: 20.0,
            sizeLabel: "20 oz",
            caffeineMg: 198,
            region: "US",
            sourceName: "Red Bull US Q&A",
            sourceType: .brandOfficial,
            sourceURL: "https://www.redbull.com/us-en/energydrink/questions/how-much-caffeine-is-in-a-can-of-red-bull-energy-drink",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .energy
        ),

        // Coca-Cola (US)
        BrandProductPreset(
            id: "us-cocacola-original-12oz",
            brand: "Coca-Cola",
            productName: "Coca-Cola Original",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 34,
            region: "US",
            sourceName: "The Coca-Cola Company / Coca-Cola US",
            sourceType: .brandOfficial,
            sourceURL: "https://www.coca-cola.com/us/en/brands/coca-cola/products/original",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-cocacola-zero-sugar-12oz",
            brand: "Coca-Cola",
            productName: "Coca-Cola Zero Sugar",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 34,
            region: "US",
            sourceName: "The Coca-Cola Company / Coca-Cola US",
            sourceType: .brandOfficial,
            sourceURL: "https://www.coca-cola.com/us/en/brands/coca-cola/products/zero",
            lastVerifiedAt: "2026-02-24",
            notes: "Official page says about 34 mg.",
            category: .soda
        ),
        BrandProductPreset(
            id: "us-diet-coke-12oz",
            brand: "Coca-Cola",
            productName: "Diet Coke",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 46,
            region: "US",
            sourceName: "The Coca-Cola Company / Coca-Cola US",
            sourceType: .brandOfficial,
            sourceURL: "https://www.coca-cola.com/us/en/brands/diet-coke/products",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-barqs-root-beer-12oz",
            brand: "Coca-Cola",
            productName: "Barq's Root Beer",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 22,
            region: "US",
            sourceName: "The Coca-Cola Company / Coca-Cola US",
            sourceType: .brandOfficial,
            sourceURL: "https://www.coca-cola.com/us/en/brands/barq-s",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-sprite-12oz",
            brand: "Coca-Cola",
            productName: "Sprite",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 0,
            region: "US",
            sourceName: "The Coca-Cola Company / Coca-Cola US",
            sourceType: .brandOfficial,
            sourceURL: "https://www.coca-cola.com/us/en/brands/sprite/products",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-fresca-12oz",
            brand: "Coca-Cola",
            productName: "Fresca",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 0,
            region: "US",
            sourceName: "The Coca-Cola Company / Coca-Cola US",
            sourceType: .brandOfficial,
            sourceURL: "https://www.coca-cola.com/us/en/brands/fresca-sparkling-soda",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),

        // Pepsi (US)
        BrandProductPreset(
            id: "us-pepsi-12oz",
            brand: "Pepsi",
            productName: "Pepsi",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 38,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000000133",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-diet-pepsi-12oz",
            brand: "Pepsi",
            productName: "Diet Pepsi",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 35,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000008054",
            lastVerifiedAt: "2026-02-24",
            notes: "Some sources/listings report 34 mg, but this Product Facts SKU page lists 35 mg for 12 oz.",
            category: .soda
        ),
        BrandProductPreset(
            id: "us-pepsi-zero-sugar-12oz",
            brand: "Pepsi",
            productName: "Pepsi Zero Sugar",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 38,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000018770",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-pepsi-mini-7_5oz",
            brand: "Pepsi",
            productName: "Pepsi",
            sizeOz: 7.5,
            sizeLabel: "7.5 oz mini can",
            caffeineMg: 24,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000163135",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-diet-pepsi-mini-7_5oz",
            brand: "Pepsi",
            productName: "Diet Pepsi",
            sizeOz: 7.5,
            sizeLabel: "7.5 oz mini can",
            caffeineMg: 22,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000171970",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-pepsi-zero-sugar-mini-7_5oz",
            brand: "Pepsi",
            productName: "Pepsi Zero Sugar",
            sizeOz: 7.5,
            sizeLabel: "7.5 oz mini can",
            caffeineMg: 24,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000180217",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),

        // Mountain Dew (US)
        BrandProductPreset(
            id: "us-mtn-dew-12oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 54,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000000850",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-diet-mtn-dew-12oz",
            brand: "Mountain Dew",
            productName: "Diet Mountain Dew",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 54,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000001666",
            lastVerifiedAt: "2026-02-24",
            notes: "PepsiCo Product Facts page title may display '(can)' for this SKU.",
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-zero-sugar-12oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Zero Sugar",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 68,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000191466",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-zero-sugar-16oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Zero Sugar",
            sizeOz: 16.0,
            sizeLabel: "16 oz",
            caffeineMg: 90,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000192937",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-zero-sugar-16_9oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Zero Sugar",
            sizeOz: 16.9,
            sizeLabel: "16.9 oz",
            caffeineMg: 95,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000192722",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-zero-sugar-20oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Zero Sugar",
            sizeOz: 20.0,
            sizeLabel: "20 oz",
            caffeineMg: 113,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000191435",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-code-red-12oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Code Red",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 54,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000000621",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-code-red-16_9oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Code Red",
            sizeOz: 16.9,
            sizeLabel: "16.9 oz",
            caffeineMg: 77,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000102059",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-code-red-20oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Code Red",
            sizeOz: 20.0,
            sizeLabel: "20 oz",
            caffeineMg: 91,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000002243",
            lastVerifiedAt: "2026-02-24",
            notes: nil,
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-baja-blast-12oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Baja Blast",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 59,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000130311",
            lastVerifiedAt: "2026-02-24",
            notes: "Can/bottle packaging value; fountain versions may differ.",
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-baja-blast-16oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Baja Blast",
            sizeOz: 16.0,
            sizeLabel: "16 oz",
            caffeineMg: 78,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000172670",
            lastVerifiedAt: "2026-02-24",
            notes: "Can/bottle packaging value; fountain versions may differ.",
            category: .soda
        ),
        BrandProductPreset(
            id: "us-mtn-dew-baja-blast-20oz",
            brand: "Mountain Dew",
            productName: "Mountain Dew Baja Blast",
            sizeOz: 20.0,
            sizeLabel: "20 oz",
            caffeineMg: 98,
            region: "US",
            sourceName: "PepsiCo Product Facts",
            sourceType: .brandOfficial,
            sourceURL: "https://www.pepsicoproductfacts.com/Home/product?gtin=00012000130274",
            lastVerifiedAt: "2026-02-24",
            notes: "Can/bottle packaging value; fountain versions may differ.",
            category: .soda
        ),

        // CELSIUS (US)
        BrandProductPreset(
            id: "us-celsius-standard-12oz",
            brand: "CELSIUS",
            productName: "CELSIUS (standard can)",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 200,
            region: "US",
            sourceName: "CELSIUS Official",
            sourceType: .brandOfficial,
            sourceURL: "https://www.celsius.com/essential-facts/",
            lastVerifiedAt: "2026-02-24",
            notes: "Official page lists caffeine by product line. Flavor-level values may vary by line.",
            category: .energy
        ),
        BrandProductPreset(
            id: "us-celsius-essentials-16oz",
            brand: "CELSIUS",
            productName: "CELSIUS Essentials",
            sizeOz: 16.0,
            sizeLabel: "16 oz",
            caffeineMg: 270,
            region: "US",
            sourceName: "CELSIUS Official",
            sourceType: .brandOfficial,
            sourceURL: "https://www.celsius.com/essential-facts/",
            lastVerifiedAt: "2026-02-24",
            notes: "Official page lists caffeine by product line. Flavor-level values may vary by line.",
            category: .energy
        ),
        BrandProductPreset(
            id: "us-celsius-hydration-12oz",
            brand: "CELSIUS",
            productName: "CELSIUS Hydration",
            sizeOz: 12.0,
            sizeLabel: "12 oz",
            caffeineMg: 0,
            region: "US",
            sourceName: "CELSIUS Official",
            sourceType: .brandOfficial,
            sourceURL: "https://www.celsius.com/essential-facts/",
            lastVerifiedAt: "2026-02-24",
            notes: "Official page lists caffeine by product line. Flavor-level values may vary by line.",
            category: .energy
        )
    ]
}
